import type { EditorialSection } from "@/components/editorial-sections"

export const COMPARISON_GUIDE: EditorialSection[] = [
  { heading: "Start with what the customer will accept", paragraphs: [
    "Ask the buyer to describe the assurance it requires, including the service boundary, report or certificate type and any timing constraints. A request for a SOC 2 Type II report is different from a request for an information security policy or an ISO 27001 certificate. Clarify whether the requirement is mandatory for procurement or one possible way to demonstrate security. Document the answer so that the programme is tied to a real commercial need rather than a general preference for a familiar badge.",
    "Review the scope the buyer expects against the services you actually operate. A certificate covering one entity or location may not answer a question about another product. A report on a specific system may not cover the entire company. Read both scope and intended use before promising that an existing assurance document satisfies the request. Where requirements conflict, involve the customer and the relevant independent auditor or certification body early.",
  ] },
  { heading: "Understand the different evidence models", paragraphs: [
    "ISO 27001 examines an information security management system, including how the organisation understands risk, makes control decisions and reviews improvement. Evidence connects policies, implementation, internal audit and management review. SOC 2 examines specified controls using the applicable Trust Services Criteria and the system description. Both can involve access management, change control, incident handling and supplier processes, but the auditor's objectives and required records are not identical.",
    "SOC 2 Type I addresses control design at a point in time. Type II also addresses operating effectiveness over a stated period. Creating a control today does not produce valid evidence that it operated earlier. Plan the observation period and collection of real records with the CPA firm. Similarly, preparing an ISO policy library is not the same as operating an ISMS that can be independently audited. Neither programme should be represented as a document purchase with a guaranteed outcome.",
  ] },
  { heading: "Reuse controls without merging the audit outcomes", paragraphs: [
    "A shared control inventory can reduce duplicated operational work. For each control, record the owner, purpose, relevant systems, activity frequency and evidence retained. Link it to the requirements it supports while noting differences in scope or testing. An access review may contribute to both programmes, but the population, period and auditor's examination needs can differ. Validate the mapping rather than assuming that a general control description meets every requirement.",
    "Maintain consistent records of real activity and secure the evidence repository. Avoid creating competing versions of policies for different auditors unless there is a genuine scope difference. Keep exceptions, changes and remediation visible to the responsible owners. The resulting reports and certificates remain separate: an ISO 27001 certification body does not grant a SOC 2 report, and a CPA attestation does not automatically certify an ISMS. Reuse evidence where appropriate without advertising one result as the other.",
  ] },
  { heading: "Budget for operation, not just the final document", paragraphs: [
    "Preparation effort depends on the environment and existing maturity. A team may need technical remediation, process changes, supplier reviews or additional capacity for evidence collection. Independent audit or examination fees are separate from readiness assistance. Ask what the proposal includes, what your staff must do and how exclusions are handled. A fixed price or timetable quoted without scope can hide important work rather than simplify the decision.",
    "Choose providers with clear roles. Readiness support can help assess gaps and prepare evidence, while the independent reviewer determines the audit outcome. After completion, continue operating controls and plan required maintenance or subsequent examination. Product changes, new infrastructure and supplier changes can affect the boundary and evidence. The assurance remains useful only when customers can understand what it covers and the organisation continues managing the associated risk.",
  ] },
  { heading: "A practical sequence for a growing SaaS company", paragraphs: [
    "First confirm the customer requirement and define the relevant service scope. Then assess current controls, assign owners and prioritise gaps that would undermine the intended assurance. Discuss examination or certification arrangements with the appropriate independent firm. Establish a sustainable evidence process before committing to a date. Where both programmes are needed, plan shared work and separate review milestones rather than restarting the same tasks in two disconnected projects.",
    "Treat this as a planning approach, not a promised customer result or a universal order. Customer priorities, the maturity of controls and the organisation's capacity can change the sequence. Use the readiness assessment to make that decision explicit, record limitations and review progress. Detailed definitions in the glossary can help the technical, procurement and leadership teams use the same terminology during the discussion.",
  ], links: [{ href: "/glossary/soc-2", label: "SOC 2 attestation explained" }, { href: "/glossary/iso-27001", label: "ISO 27001 and the ISMS" }] },
]
