import type { EditorialSection } from "@/components/editorial-sections"
import type { Hub } from "@/lib/services"

export const SERVICE_NOTES: Record<string, string> = {
  "managed-soc": "Managed SOC brings monitoring, investigation and escalation into an agreed operating model. Begin with the systems and identities that support critical services, then define log collection, coverage hours, access and response permissions. A useful scope distinguishes notifying your team from investigating an alert or helping contain an incident. Review escalation contacts, evidence handling and reporting before onboarding. Monitoring can support compliance evidence, but it does not itself confer certification or guarantee prevention of every attack. Explore the service for provider-selection guidance and the responsibilities to agree before deployment.",
  "soc-as-a-service": "SOC as a Service provides security-operations capability through an external delivery arrangement. It can help an organisation access analyst support and monitoring technology without building every capability internally. The engagement still needs clear boundaries: which assets are supported, what data is collected, who investigates and who approves response actions. Check compatibility with existing endpoint, cloud and identity systems, and establish a route for urgent decisions. Choose the model based on the operating coverage you need rather than assuming that every subscription includes the same tooling or incident-response work.",
  vapt: "Vulnerability assessment and penetration testing identify weaknesses and test selected attack paths within authorised boundaries. Agree assets, environments, testing windows, exclusions and emergency contacts before work begins. Automated tools can identify known patterns, while manual assessment explores context and exploitability. Request findings that explain business impact and practical remediation rather than a raw scanner export. Assign owners for fixes and clarify how retesting will validate completion. The service can support release decisions and customer assurance, but a successful test does not guarantee that every vulnerability has been found.",
  "endpoint-security": "Endpoint security addresses the devices people and applications use to access your business systems. Begin with a reliable inventory, supported operating systems, administrative rights and clear ownership. Protection technology needs appropriate configuration, ongoing maintenance and a process for investigating suspicious activity. Decide who can isolate a device, how users receive support and how exceptions are reviewed. Consider remote workers and devices that cannot run the same controls as standard laptops. Coordinate endpoint work with identity management, monitoring and patching so that alerts can lead to an accountable action.",
  "firewall-network-security": "Firewall and network security help control connections between users, systems and external services. Effective rules reflect actual business flows rather than an inherited configuration that nobody can explain. Document network boundaries, remote access and administrative access, then review allowed traffic and unnecessary exposure. Changes should have an owner, testing plan and rollback path because restricting a connection can interrupt a critical application. Logging and rule reviews support investigation, but a firewall cannot replace secure application design or strong identity controls. Use the service to align connectivity with the risks of your environment.",
  "email-security": "Email security combines technical protection with processes for handling suspicious messages and compromised accounts. Review authentication, mailbox access, filtering and the way users report potential phishing. Determine who investigates a reported message and how the team responds if an account has already been misused. Controls should consider supplier impersonation and changes to payment instructions as well as malicious attachments. User education is useful but cannot carry the entire burden. Connect email alerts with identity and incident-response practices so that suspected abuse is investigated with appropriate business context.",
  "incident-response": "Incident response prepares an organisation to assess, contain and recover from security events. A plan should identify technical and business decision-makers, communication routes, evidence handling and authority for disruptive actions. Readiness work can expose missing contacts and unclear responsibilities before an emergency occurs. During an incident, decisions depend on the actual systems, evidence and business impact; not every situation should trigger the same response. Agree the support available, access prerequisites and any exclusions. Afterward, review the causes and corrective actions without treating restoration of service as the end of the security investigation.",
  "risk-assessment": "A cybersecurity risk assessment connects technical exposure to the organisation's services, data and operational priorities. Start by defining the assessment boundary and the consequences of disruption, disclosure or unauthorised change. Review existing controls and relevant dependencies, then prioritise improvements using impact and likelihood in the business context. Findings should have accountable owners and a way to track treatment or acceptance. The assessment is not simply a vulnerability scan or a product recommendation. Revisit decisions when infrastructure, suppliers or customer requirements change so that the risk register remains a useful management tool.",
  consulting: "Cybersecurity consulting helps teams translate risk and customer obligations into a practical programme. The starting point may be a governance question, an architecture review or a decision about security providers. Define the desired deliverable and who will use it before committing to the engagement. Recommendations should explain priorities, responsibilities and dependencies rather than assume that buying a particular tool solves the problem. Clarify what implementation support is included and which work remains with your internal team. Advice is most useful when it can be tracked against an agreed scope and reviewed as the business changes.",
  "iso-27001": "ISO 27001 work establishes and improves a defined information security management system. Begin with organisational context, scope, risk assessment and control ownership, then build records showing that relevant processes operate in practice. Policies alone are not sufficient preparation for an independent audit. Readiness consulting and remediation support are distinct from the certification body's audit and certification decision. Plan evidence, internal review and management oversight alongside technical controls. The service page explains scope and cost factors so that teams can prepare a programme appropriate to their customer obligations without assuming a fixed price or guaranteed certification.",
  "iso-42001": "ISO 42001 addresses an artificial intelligence management system within a defined scope. Organisations using, developing or supplying AI should first understand their role, affected processes and applicable obligations. Management-system work connects governance, risk decisions and operational responsibilities rather than treating AI assurance as a single model test. Document relevant systems, oversight and evidence, and identify who approves changes. Independent certification remains separate from readiness assistance. Use the service to explore the framework and establish which activities actually belong in your programme before choosing audit timing or making claims about organisational certification.",
  "iso-9001": "ISO 9001 concerns a quality management system and the processes used to deliver products or services consistently. Scope the organisation's activities, customer requirements and process responsibilities before preparing documentation. Define how quality objectives, feedback, corrective action and management review operate in everyday work. Readiness assistance may help teams assess gaps and organise evidence, while an independent certification body makes the certification decision. Avoid reducing the programme to a collection of templates. A useful management system should connect records to actual delivery processes and be maintained as services, teams and customer expectations change.",
  gdpr: "GDPR readiness starts with applicability, processing purposes and the organisation's controller or processor roles. Map personal-data flows and assess lawful bases, transparency, rights handling, retention and relevant supplier arrangements. Technical security supports privacy but does not replace accountable decisions about processing. An Indian location does not automatically rule GDPR applicability in or out. Use appropriate legal advice for interpretation and cross-border obligations. The service can help organise a practical readiness programme; it should not be mistaken for a universal GDPR certificate or a guarantee that every business activity is compliant.",
  "pci-dss": "PCI DSS addresses security requirements for environments relevant to payment card account data. Map the payment journey and identify systems that store, process or transmit data, or can affect the security of that environment. Outsourcing part of payment processing does not automatically remove every responsibility. Establish the applicable validation method with the relevant payment stakeholders and assess actual eligibility rather than selecting a familiar questionnaire by default. Readiness work includes scoping, gap assessment and remediation. Keep operational evidence current and revisit scope when checkout integrations, infrastructure or payment providers change.",
  hipaa: "HIPAA readiness requires a careful assessment of covered-entity or business-associate roles and relevant protected health information. An Indian supplier supporting a US healthcare service may have obligations depending on its activities and contracts; the industry label alone does not determine applicability. Review information flows, safeguards, risk analysis, supplier arrangements and incident procedures with appropriate specialists. Readiness assistance supports operational improvement, not an official HHS-issued organisational certificate. Define which data and systems are in scope and maintain evidence of the relevant controls rather than relying on a generic healthcare policy pack.",
  soc2: "SOC 2 readiness prepares a service organisation for an independent CPA controls examination. It is not a certification or a Security Operations Centre service. Determine the report boundary, applicable Trust Services Criteria and the customer need for Type I or Type II assurance. Assign owners for controls, remediate gaps and retain evidence of actual operation. A platform or consultant cannot promise the auditor's opinion. The service page includes preparation and provider-selection guidance and explains how readiness, independent examination and continuing control operation contribute to the overall engagement.",
  "dpdp-act": "DPDP readiness concerns India's personal-data protection framework and the obligations applicable to the organisation's activities. Map data flows, processing purposes, notices, supplier relationships and responsibility for operational decisions. Check the current legal requirements and commencement of relevant provisions with qualified advisers rather than assuming every duty applies on the same date. Security controls can support data protection, but privacy work also needs governance and processes for handling relevant requests and incidents. Define a practical scope and keep the programme under review as systems, contracts and applicable rules change.",
  "managed-it-services": "Managed IT services organise ongoing support and maintenance around a defined environment. Inventory users, devices, applications and infrastructure before agreeing ownership, service hours and escalation priorities. Separate routine support from projects and specialist security work so that responsibilities are visible. A useful reporting process shows outstanding issues, recurring problems and relevant changes rather than only ticket totals. Agree access controls and approval for disruptive work. Review the scope as the business grows, ensuring that new systems and suppliers do not fall between your internal team and the external support arrangement.",
  "cloud-infrastructure": "Cloud infrastructure management supports the operation of hosted workloads, networks, storage and related identities. Establish account ownership, administrative permissions and the shared-responsibility boundary with the cloud provider. Review configuration, availability dependencies, monitoring and change approval in the context of the applications being supported. Cloud services still need maintenance and incident decisions; moving a workload does not remove operational accountability. Agree how usage, service health and configuration risks will be reviewed. Coordinate with security and backup processes so that administrators can respond to problems without relying on undocumented access or assumptions.",
  "cloud-migration": "Cloud migration moves workloads and data through a planned transition rather than a single copying exercise. Assess dependencies, target architecture, access, security and operational responsibilities before selecting a migration path. Establish testing, acceptance criteria and a rollback decision for each stage. Plan how users, suppliers and support teams will be informed of changes. The appropriate sequence depends on the application's availability and data requirements, so universal downtime or savings promises are not useful. Include post-migration validation and operating handover to ensure the environment can be supported after the project ends.",
  "cloud-optimization": "Cloud optimisation reviews resource use and architecture against performance, availability and cost requirements. Begin with reliable usage and billing information, workload owners and the reasons particular resources were provisioned. Right-sizing or removing unused resources can help, but changes must preserve application requirements and recovery arrangements. Establish approval and testing before altering capacity or purchasing commitments. Separate demonstrated savings from projections and consider the period used for comparison. Ongoing review is valuable because demand, pricing models and architecture change; a one-off exercise cannot guarantee a fixed reduction in every environment.",
  "backup-disaster-recovery": "Backup and disaster recovery protect different parts of a continuity plan. Backups retain recoverable copies, while recovery planning addresses how services will be restored after disruption. Define the systems, acceptable data loss and restoration priorities, then test whether the chosen arrangements can meet those needs. Include access, dependencies and responsible decision-makers in recovery exercises. A completed backup job is not proof that an application can be restored. Review protection when workloads or suppliers change and keep test records, unresolved failures and follow-up actions visible to the people responsible for business continuity.",
  "helpdesk-support": "Helpdesk support provides a clear route for users to report problems and request assistance. Define which users and systems are covered, how requests are prioritised and which issues require specialist escalation. Account access, device changes and supplier coordination need documented approval boundaries rather than informal workarounds. Track recurring problems and use them to improve underlying processes, not simply close individual tickets. Service hours and response expectations should match the agreed scope. Coordinate the helpdesk with security and infrastructure teams so that suspicious activity and important operational failures reach the appropriate owners.",
}

export const HUB_GUIDES: Record<Hub, EditorialSection[]> = {
  cybersecurity: [
    { heading: "How we work: scope, prioritise and review", paragraphs: [
      "Begin with the services and information your organisation must protect. Identify critical assets, external exposure, privileged access and suppliers that can affect those assets. Discuss the consequences of disruption with business owners instead of relying only on a technical severity score. This establishes why particular work is needed and what an initial assessment should cover.",
      "Turn findings into an owned improvement plan. Testing, monitoring and incident readiness address different parts of the problem, so decide where each contributes and where existing staff already have capability. Agree deliverables, access approvals, reporting and escalation before work begins. Record exclusions explicitly, including systems that cannot be tested or monitored safely. Any implementation change should have an approver, validation and a way to reverse an unexpected operational impact.",
      "Review progress using evidence relevant to the agreed scope. Useful measures can include validated remediation, monitored-source coverage and completion of response exercises. They should not be presented as proof that a breach is impossible. Update priorities after important product releases, infrastructure changes or incidents. Security work needs ongoing ownership even when delivery is supported by an external provider.",
    ] },
    { heading: "Who we work with", paragraphs: [
      "Startups need right-sized controls and credible customer assurance without implying that every early-stage company needs the same toolset. Healthcare and BFSI teams need security work that reflects sensitive data, service continuity and actual regulatory responsibilities. E-commerce and fintech teams need to consider payment integrations, customer identities and the effects of transaction peaks. Our industry pages explain the decisions to scope before choosing services; they are guidance, not claims that one package covers every organisation in a sector.",
    ], links: industryLinks() },
  ],
  compliance: [
    { heading: "How we work: requirements, controls and evidence", paragraphs: [
      "Start with the requirement that is driving the programme. It may be a customer contract, an independent report request, a certification objective or a legal obligation. Those outcomes are not interchangeable. Define the relevant entity, service, systems and data, and use qualified legal or audit specialists for decisions that require their authority. The scope should explain what is covered and what remains outside the engagement.",
      "Assess gaps against that boundary and assign control owners. Distinguish a missing document from a process that does not operate or a technical weakness that needs remediation. Policies, access controls, supplier procedures and incident processes need records of real activity. Schedule work with teams that can make the changes, and agree how evidence will be collected securely. Avoid promises of a guaranteed audit result or a fixed timetable before maturity and scope are assessed.",
      "Prepare for the appropriate independent review and continue operating the controls afterward. Consulting supports readiness; certification bodies and CPA firms make their own audit decisions. A privacy programme may not involve a certification at all. Use internal reviews, management oversight and change tracking to keep evidence aligned with the live organisation. When two programmes overlap, reuse relevant records while preserving the separate scope and requirements of each.",
    ] },
    { heading: "Who we work with", paragraphs: [
      "A startup may be deciding whether a customer needs SOC 2, ISO 27001 or a focused security questionnaire response. Healthcare and financial-services teams need to distinguish their actual legal and contractual duties from broad sector labels. E-commerce and fintech teams may need payment-security and privacy programmes with different boundaries. These industry guides help establish context for the readiness assessment. The appropriate programme is determined by the organisation's services, data and customers, not by a generic promise of certification.",
    ], links: industryLinks() },
  ],
  "it-managed-services": [
    { heading: "How we work: ownership before day-to-day support", paragraphs: [
      "Begin with an inventory of users, endpoints, applications, infrastructure and cloud accounts. Record who owns each service and which suppliers provide essential dependencies. Establish the existing support arrangements and the problems that are causing disruption. This makes it possible to define a service boundary rather than assuming an external team will take responsibility for every technology-related issue.",
      "Agree support hours, priorities, administrative access, reporting and approval for changes. Separate ongoing operations from migration projects, application development and specialist security activities. Define how a routine ticket becomes an incident and how urgent decisions reach the internal owner. Document access removal when staff or suppliers change. A reliable service depends on clear responsibilities as much as on monitoring tools.",
      "Review recurring issues, patch and configuration work, backup results and important changes. Test restoration and handover arrangements instead of treating a healthy dashboard as proof of continuity. Capacity and cost decisions should preserve application requirements and have appropriate validation. Revisit the scope as users, workloads and suppliers change, keeping exclusions and outstanding risks visible. The objective is accountable operation of the agreed environment, not a promise that every outage can be prevented.",
    ] },
    { heading: "Who we work with", paragraphs: [
      "Startups often need a support structure that grows with their workforce and cloud estate. Healthcare and BFSI environments need maintenance decisions that respect sensitive data and continuity requirements. E-commerce and fintech platforms need operational ownership across peaks in traffic, payment dependencies and recovery planning. Our industry pages connect these concerns to the service choices available. Coverage hours, availability targets and specialist responsibilities are agreed for each engagement rather than inferred from an industry label.",
    ], links: industryLinks() },
  ],
}

function industryLinks() {
  return [
    { href: "/industries/startups", label: "Startups and scaleups" },
    { href: "/industries/healthcare-bfsi", label: "Healthcare and BFSI" },
    { href: "/industries/ecommerce-fintech", label: "E-commerce and fintech" },
  ]
}
