import type { EditorialSection } from "@/components/editorial-sections"

export const GLOSSARY_INDEX_GUIDE: EditorialSection[] = [
  { heading: "Use the glossary to make a practical decision", paragraphs: [
    "Security and compliance terminology often combines an operating capability, a technical tool and an assurance outcome in the same conversation. This glossary separates those concepts. Start with a definition, then read the practical explanation, comparison and misconceptions. The aim is to help business and technical teams agree what work is needed, who owns it and which evidence supports a decision. A definition alone should not be interpreted as legal advice, a certification claim or a complete implementation checklist.",
    "For operational security, begin with VAPT, SOC and SIEM. VAPT helps identify and validate weaknesses within an authorised scope. A SOC investigates security activity and coordinates response. SIEM supports collection and analysis of events. These can complement each other without being substitutes. Agree the systems, access, responsibilities and response decisions relevant to your environment before selecting a service.",
    "For assurance and compliance, distinguish management-system certification, independent attestation and legal or payment-security obligations. ISO 27001 concerns an ISMS; SOC 2 is a CPA controls report. GDPR and HIPAA applicability need assessment of the organisation's role and processing activities. PCI DSS scope depends on the payment environment and relevant responsibilities. A common label used in procurement is not enough to determine which requirements apply.",
    "Each entry includes reference sources and a contextual service link where one is relevant. Use official authorities for the governing requirements and qualified specialists for interpretation. Read related terms when acronyms are easily confused, particularly SOC and SOC 2. If you are discussing work with a provider, ask for a scoped deliverable and clear exclusions. Revisit the definition and the operating boundary when products, customers or suppliers change, rather than treating a programme as complete because a document has been issued.",
  ] },
]

export const INDUSTRIES_INDEX_GUIDE: EditorialSection[] = [
  { heading: "Find the right context before selecting services", paragraphs: [
    "Industry context helps explain why a security or compliance requirement matters, but it does not replace scoping. Two organisations in the same sector can operate different products, handle different data and have different contractual responsibilities. Begin with the services customers rely on, the information involved and the impact of interruption or disclosure. Then identify relevant legal obligations and assurance requests with appropriate specialists.",
    "Our industry guides connect those questions to cybersecurity, compliance and managed IT choices. They describe practical decisions and possible engagement outputs, not a universal package or fabricated customer results. Use them to prepare a discussion with your internal owners and prospective providers. A clear scope should identify the systems, data, deliverables, approvals and exclusions that matter in your own environment.",
  ] },
  { heading: "Startups and scaleups", paragraphs: [
    "Growing product teams often need to answer enterprise security questionnaires while maintaining release speed and controlling operational overhead. The first step is to distinguish what priority customers actually require from generic assurance preferences. Map the production environment and privileged access, then choose controls the team can operate consistently. SOC 2 and ISO 27001 have different outcomes, so a buyer-led sequence can avoid pursuing the wrong document. The startup guide covers product testing, evidence ownership and the information to bring to a scoped review.",
  ], links: [{ href: "/industries/startups", label: "Security and assurance for startups" }] },
  { heading: "Healthcare and BFSI", paragraphs: [
    "Sensitive information, continuity and specialist systems can shape security decisions in healthcare and financial services. Maintenance or containment actions need operational context, particularly where disruption affects care or transactions. Establish the actual legal and contractual duties rather than assuming HIPAA, PCI DSS or one certification applies to every organisation under a sector label. The guide explains how to map data and service dependencies, plan safe changes and coordinate incident ownership. It also distinguishes consulting from legal interpretation and independent audit decisions.",
  ], links: [{ href: "/industries/healthcare-bfsi", label: "Healthcare and BFSI risk and readiness" }] },
  { heading: "E-commerce and fintech", paragraphs: [
    "Transaction platforms connect customer identities, applications, payment providers, cloud infrastructure and support teams. The full journey matters because sensitive information and privileged access can appear outside the primary payment system. Scope testing carefully where an action could initiate a real transaction. Assess applicable payment-security and privacy requirements separately, and coordinate monitoring with business fraud decisions. The guide covers application testing, operational peaks and recovery planning, with links to relevant service options rather than claims that one tool protects every transaction.",
  ], links: [{ href: "/industries/ecommerce-fintech", label: "E-commerce and fintech service planning" }] },
  { heading: "Prepare for an initial scoping conversation", paragraphs: [
    "Bring an overview of the services, applications and suppliers involved, a description of sensitive data categories and the requirements customers or regulators have raised. Include existing testing, monitoring, support and recovery arrangements. Identify who can approve access, changes and risk decisions. Sanitised descriptions are enough for an initial discussion; do not share live customer, patient or payment records merely to demonstrate a concern.",
    "A useful next step is an agreed assessment boundary and a prioritised plan with accountable owners. Some work will be technical, while other decisions need governance, legal or independent audit input. Review timing, coverage and exclusions before committing. Keep the plan current as services and suppliers change, and distinguish projected improvements from validated outcomes.",
  ], links: [{ href: "/contact", label: "Discuss your industry and service scope" }] },
]

export const BLOG_INTRO = "These guides explain cybersecurity, compliance and managed IT decisions for teams planning real work. Start with the question your organisation needs to answer: which systems require testing, what monitoring should cover, how a customer assurance request affects scope, or how infrastructure changes will be supported. Each article should be read alongside the relevant service requirements and current official guidance. A blog is not a substitute for legal advice, an independent audit or a scoped technical assessment. Use definitions and comparisons to align terminology across business and technical teams, then identify responsible owners and evidence for the next decision. Where an article discusses possible workflows, treat them as planning examples unless a documented customer result is explicitly provided. Our service pages explain engagement options and responsibilities. If your environment, customer commitments or suppliers have changed, revisit earlier assumptions before applying a recommendation. Clear scope matters more than a generic checklist alone."
