import type { EditorialSection } from "@/components/editorial-sections"

export const INDUSTRY_GUIDES: Record<string, EditorialSection[]> = {
  startups: [
    { heading: "Begin with customer requirements and product risk", paragraphs: [
      "A startup's first security programme should reflect the product it operates and the customers it hopes to serve. Collect the assurance requests from priority buyers and identify which are contractual requirements, which are preferences and which ask for evidence you can already provide. A customer may need a SOC 2 report, an ISO 27001 certificate or answers to a focused questionnaire; those requests should not be treated as interchangeable.",
      "Map the production environment, customer data, privileged accounts and suppliers that support the product. Identify how development and deployment changes are approved and who can access sensitive information. This establishes a practical boundary for testing and readiness work. The objective is to make honest, evidence-backed commitments, not to promise a mature enterprise programme before the team has the capacity to operate one.",
    ] },
    { heading: "Build controls into the way the team works", paragraphs: [
      "Assign owners for access reviews, onboarding and offboarding, vulnerability remediation and incident decisions. These responsibilities may sit with existing staff rather than a dedicated security department, but they still need time and clear authority. Connect security checks to release and infrastructure processes so that they do not depend on somebody remembering an informal task. Keep evidence of actual work where customer assurance or an audit requires it.",
      "Prioritise changes that address meaningful product risk. A testing engagement needs agreed boundaries and a plan for fixing findings. Monitoring needs usable logs and somebody who can respond to escalation. A backup needs a restoration test and a decision about acceptable data loss. Document any deferred improvement with an owner and review date, avoiding unsupported claims that a tool purchase has resolved every exposure.",
    ] },
    { heading: "Choose an assurance sequence that the business can sustain", paragraphs: [
      "Discuss report or certification scope before signing a readiness contract. A narrow product boundary and a company-wide programme have different evidence needs. Distinguish the readiness provider's work from the independent auditor's role and ensure the team understands ongoing obligations. The programme should continue after the procurement deadline, not stop when a customer receives a document.",
      "Where several frameworks are requested, reuse operational evidence where appropriate without assuming that one outcome grants another. Compare customer demand, scope and team capacity before deciding which to pursue first. Our SOC 2 and ISO 27001 comparison explains that decision in more detail. Cost and timing depend on maturity and the work required; they should be scoped rather than promised from a generic checklist.",
    ], links: [{ href: "/compare/soc-2-vs-iso-27001", label: "Compare SOC 2 and ISO 27001" }] },
    { heading: "What to bring to an initial discussion", paragraphs: [
      "Bring a product and infrastructure overview, important customer assurance requests, a list of data categories and current support arrangements. Identify the internal contact who can approve access and the person responsible for business risk decisions. Useful engagement outputs include a scoped gap assessment, a prioritised remediation plan and evidence or monitoring responsibilities that the team can maintain. These are planning examples, not claims about a particular customer's results. Review the plan after new funding, market entry, an important product launch or a significant change in suppliers.",
      "Set an internal review date for outstanding findings and procurement commitments. Confirm that any assurance statement used in sales describes the actual product scope and the evidence available. If coverage or staffing changes, update the commitment before repeating it to another customer.",
    ], links: [{ href: "/compliance/soc2", label: "SOC 2 readiness" }, { href: "/cybersecurity/vapt", label: "Product security testing" }, { href: "/contact", label: "Discuss your startup's scope" }] },
  ],
  "healthcare-bfsi": [
    { heading: "Distinguish the service, the data and the obligation", paragraphs: [
      "Healthcare and financial-services organisations should begin with the services they deliver and the information they handle. A clinical system, a payment application and a back-office support platform have different dependencies and risks. Map critical workflows and the consequences of downtime before choosing security controls. Protecting confidentiality matters, but availability and the integrity of records can be equally important to safe, reliable operation.",
      "Identify actual legal, contractual and sector requirements with the relevant specialists. HIPAA applicability depends on covered-entity or business-associate roles and the relevant US healthcare information; it should not be assumed for every Indian healthcare business. PCI DSS concerns applicable payment-card environments. Financial-sector requirements also depend on the organisation's role. A broad industry label does not establish that one compliance package addresses every obligation.",
    ] },
    { heading: "Plan changes around operational continuity", paragraphs: [
      "Testing, patching and monitoring need agreed boundaries for systems supporting care or financial transactions. Legacy equipment and specialist applications may have limitations that standard endpoint controls do not address. Consult operational owners before scanning, deploying an agent or isolating a system. Record exclusions and compensating controls so that important risk is visible rather than hidden by a dashboard that only shows supported devices.",
      "Recovery planning should identify the applications that must return first, the dependencies needed for restoration and acceptable data loss. Test the process with appropriate safeguards and keep records of failures and follow-up actions. A successful backup job does not prove that the complete service can be recovered. Supplier support, administrative access and communication routes need to be available when an incident occurs.",
    ] },
    { heading: "Make incident and evidence ownership explicit", paragraphs: [
      "A security event may require coordinated technical, legal and operational decisions. Establish who investigates, who approves containment and who assesses any notification obligations. Logs and incident records can help reconstruct activity, but access to them must respect sensitive information. Managed monitoring should have a documented escalation path and a clear distinction between analyst recommendations and actions the internal team must perform.",
      "Readiness and audit work should reflect those operating arrangements. Assign owners for access reviews, vendor assessments, change approval and incident processes according to the applicable framework. Independent certification or examination remains separate from consulting. Review the scope after changes to systems, outsourcing or service delivery so that controls and evidence continue to describe the actual environment.",
    ] },
    { heading: "What to prepare for a scoped review", paragraphs: [
      "An initial discussion is more useful with a service inventory, data-flow overview, supplier list and the specific requirements that customers or regulators have raised. Include operational restrictions, critical maintenance windows and existing recovery arrangements. A review can then distinguish urgent technical remediation, governance gaps and work requiring legal or specialist audit input. Do not share patient or customer records merely to illustrate a requirement; sanitised descriptions are usually enough for initial scoping. Outcomes and schedules depend on the agreed boundary and findings, not on an assumed sector-wide result.",
      "Agree how findings will reach the teams able to implement them. A clinical application owner, payment operations lead and infrastructure administrator may need different information from the same assessment. Reports should preserve necessary technical evidence while limiting disclosure of sensitive records. Escalate unresolved risks to the authorised business owner and record the decision. Check that proposed maintenance or containment actions remain appropriate to the current operating environment.",
    ], links: [{ href: "/compliance/hipaa", label: "HIPAA readiness scope" }, { href: "/compliance/pci-dss", label: "Payment security readiness" }, { href: "/it-managed-services/backup-disaster-recovery", label: "Backup and recovery planning" }] },
  ],
  "ecommerce-fintech": [
    { heading: "Map the complete transaction and data journey", paragraphs: [
      "E-commerce and fintech teams should map how a customer moves from account creation to payment, fulfilment and support. Identify the systems, APIs and suppliers involved at each stage. Card information, personal data, identity credentials and transaction records can have different protection requirements. Check whether sensitive data also appears in logs, analytics, test systems or support tickets, where ownership may be less clear than in the primary application.",
      "Use that map to establish applicable payment-security and privacy obligations. An external payment provider can reduce some responsibilities without eliminating every requirement around integration and the systems affecting it. GDPR and India's DPDP framework need separate applicability assessment. Security monitoring is also distinct from fraud management: a suspicious transaction can need business analysis and controls beyond a conventional infrastructure alert.",
    ] },
    { heading: "Test applications without disrupting customers", paragraphs: [
      "Plan VAPT around the actual web, mobile and API surfaces. Agree test accounts, authorised environments, rate limits and prohibited actions, especially where a test could initiate a real transaction. Assess authentication, authorisation and business logic rather than relying solely on a scanner. Assign remediation owners and validate fixes. Important releases and changes to payment integrations should prompt a review of whether previous testing still covers the relevant paths.",
      "Access controls need to cover customer accounts and administrative tools. Privileged actions, supplier access and account recovery can create different attack routes. Record who approves access and how it is removed when work ends. Coordinate application teams with operations and monitoring so that investigated activity can be understood in the context of product behaviour and approved changes.",
    ] },
    { heading: "Prepare for peaks, failures and recovery", paragraphs: [
      "Availability decisions should reflect transaction demand and the consequences of interruption. Review cloud dependencies, capacity, configuration and the way changes are tested. Optimisation can improve resource use, but reducing capacity without validating application requirements can create avoidable risk. Define which team receives alerts and who can authorise urgent changes during a traffic spike or supplier outage.",
      "Document recovery priorities, acceptable data loss and restoration dependencies. Test the process, including the permissions and supplier contacts needed to restore service. Logs can help investigation and reconciliation, but retention and access must be appropriate to the data involved. Review the plan after architecture changes rather than assuming the original backup setup protects every new component of the transaction journey.",
    ] },
    { heading: "Define useful engagement outcomes", paragraphs: [
      "Bring a transaction-flow overview, payment-provider arrangements, application inventory and existing monitoring or recovery scope to an initial review. Identify specific customer requirements and the people responsible for engineering, operations and risk decisions. Potential outputs include a payment-scope assessment, prioritised application findings and an agreed monitoring or recovery plan. These are examples of scoping deliverables, not claimed customer results. Keep security, privacy, independent validation and commercial fraud decisions distinct while coordinating the teams responsible for them. Service coverage, project timing and expected improvements must be agreed for the actual environment.",
      "Define acceptance criteria for each improvement before closing the work. A remediated API issue should be validated within the authorised test scope; a recovery change should be checked against the intended service dependency. Keep evidence of those decisions and review outstanding exceptions. Notify relevant teams when a supplier or payment integration changes, because the change can affect security, operational ownership and validation requirements at the same time. Reassess the boundary instead of extending an earlier assurance statement without checking its applicability.",
    ], links: [{ href: "/compliance/pci-dss", label: "PCI DSS readiness" }, { href: "/cybersecurity/vapt", label: "Application and API testing" }, { href: "/it-managed-services/cloud-infrastructure", label: "Cloud operations support" }] },
  ],
}
