// This file is generated automatically by Next.js
// Do not edit this file manually

type AppRoutes = "/" | "/[hub]" | "/[hub]/[slug]" | "/about" | "/authors/[slug]" | "/blog" | "/blog/[slug]" | "/blog/page/[page]" | "/careers" | "/case-studies" | "/compare/soc-2-vs-iso-27001" | "/contact" | "/ebook" | "/glossary" | "/glossary/[slug]" | "/industries" | "/industries/[slug]" | "/privacy-policy" | "/team" | "/whitepapers"
type PageRoutes = never
type LayoutRoutes = "/"
type RedirectRoutes = never
type RewriteRoutes = never
type Routes = AppRoutes | PageRoutes | LayoutRoutes | RedirectRoutes | RewriteRoutes


interface ParamMap {
  "/": {}
  "/[hub]": { "hub": string; }
  "/[hub]/[slug]": { "hub": string; "slug": string; }
  "/about": {}
  "/authors/[slug]": { "slug": string; }
  "/blog": {}
  "/blog/[slug]": { "slug": string; }
  "/blog/page/[page]": { "page": string; }
  "/careers": {}
  "/case-studies": {}
  "/compare/soc-2-vs-iso-27001": {}
  "/contact": {}
  "/ebook": {}
  "/glossary": {}
  "/glossary/[slug]": { "slug": string; }
  "/industries": {}
  "/industries/[slug]": { "slug": string; }
  "/privacy-policy": {}
  "/team": {}
  "/whitepapers": {}
}


export type ParamsOf<Route extends Routes> = ParamMap[Route]

interface LayoutSlotMap {
  "/": never
}


export type { AppRoutes, PageRoutes, LayoutRoutes, RedirectRoutes, RewriteRoutes, ParamMap }

declare global {
  /**
   * Props for Next.js App Router page components
   * @example
   * ```tsx
   * export default function Page(props: PageProps<'/blog/[slug]'>) {
   *   const { slug } = await props.params
   *   return <div>Blog post: {slug}</div>
   * }
   * ```
   */
  interface PageProps<AppRoute extends AppRoutes> {
    params: Promise<ParamMap[AppRoute]>
    searchParams: Promise<Record<string, string | string[] | undefined>>
  }

  /**
   * Props for Next.js App Router layout components
   * @example
   * ```tsx
   * export default function Layout(props: LayoutProps<'/dashboard'>) {
   *   return <div>{props.children}</div>
   * }
   * ```
   */
  type LayoutProps<LayoutRoute extends LayoutRoutes> = {
    params: Promise<ParamMap[LayoutRoute]>
    children: React.ReactNode
  } & {
    [K in LayoutSlotMap[LayoutRoute]]: React.ReactNode
  }
}
